### ISSUE TITLE
What's the maximum number of sockets that can be opened?

### ISSUE THREAD

**Issue by CoderSpinoza** [Havvy/irc-socket#13]
I see that it is not using sockets from http or https's sockets by looking at http.globalAgent,naxSockets and sockets. Is there a way to set the maximum number of sockets for simple-irc-socket?

The problem I am having is ECONNRESET error, which I suspect is due to the maximum number of sockets per host on either my irc bot server or the actual irc server. I still have to look into this issue but I was just wondering if there is any way to increase the maximum number of sockets on my node side.

**Comment by Havvy** [comment]
1) If you're using the package named 'simple-irc-socket', switch it out for 'irc-socket'. I dropped the word 'simple' a long time ago because it was fluff.

2) This is just a wrapper around a net.Socket. (Why would IRC use HTTP sockets?) Any limitations you are getting on the Node side are from net.Socket, which admittedly, I know little about.

3) If you're opening a lot of sockets to a single server, the server will stop accepting them at some point. For instance, the servers behind irc.mibbit.net only accept 3 connections each per IP. Other servers have similarly low limits. It's a protection against DoS attacks, and probably the limit you are running in to.

**Comment by CoderSpinoza** [comment]
Thanks for your explanations. Will close this issue :)
