### ISSUE TITLE
Socket.connect doesn't accept options

### ISSUE THREAD

**Issue by hohl** [Havvy/irc-socket#18]
For some reason I always end with `ECONNREFUSED` when trying your release 3.0.1. So I had a look into the source and found 

    this.impl.connect(this.connectOptions);

in line 371. However [net.Socket](https://nodejs.org/api/net.html#net_class_net_socket) class documentation doesn't mention any `connect` method which takes an object. 

When replacing that line with

    this.impl.connect(this.connectOptions.port, this.connectOptions.server);

everything seems to work for me.

**Comment by Havvy** [comment]
This is what happens when I think I know everything and forget to test on a live server...

The `ECONNREFUSED` is happening not because `net.Socket.connect(optionsObject)` doesn't exist, but because I was setting the option `"server"` instead of `"host"`. Here's the [connect Method](https://github.com/joyent/node/blob/v0.12.0-release/lib/net.js#L838) and here is [normalizeConnectArguments](https://github.com/joyent/node/blob/v0.12.0-release/lib/net.js#L97) that turns whatever you pass into `.connect()` into an object.

I actually updated the [io.js documentation](https://iojs.org/api/net.html#net_socket_connect_options_connectlistener) awhile back, but never ported my PR to Node.js.

**Comment by Havvy** [comment]
Fixed on master. Will remove the unknown message error thingy and then publish a new version.
