### ISSUE TITLE
`socket.impl.end` called before `socket.impl` emits 'connect' causes Write After End

### ISSUE THREAD

**Issue by hohl** [Havvy/irc-socket#20]
After triggering `ircSocket.end()` there still seems to be written something to the socket:

```
Uncaught Error: Uncaught, unspecified "error" event.
      at Error (native)
      at EventEmitter.<anonymous> (index.js:78:63)
      at writeAfterEnd (_stream_writable.js:169:10)
      at Socket.Writable.write (_stream_writable.js:214:5)
      at Socket.write (net.js:634:40)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:991:10)
```

(see [build log](https://travis-ci.org/hohl/irc-socket-factory/jobs/60497819#L135) or [test source](https://github.com/hohl/irc-socket-factory/blob/master/test/index.test.js#L120-L129))

**Comment by Havvy** [comment]
What in the actual fuck?

`socket.impl.on("connect") isn't being fired until *after* `socket.impl.end()` is called.

**Comment by Havvy** [comment]
This is an actual bug. It has been fixed and is in v.3.0.3. I am keeping it open because I need to backport to v.2.3.x where it also exists.

It was triggered *because* you call IrcSocket.end() before the "connect" event is emitted and then later, before the "close" event has fired, the NetSocket does emit the "connect" event.

I also notice that your tests are relying on order and a single /real/ connection. If you used IrcSocket's MockSocket (of which, you /could/ copy the one in irc-socket. In fact, if you want to, I could publish it as its own module) or made your own, you could avoid making lots of network requests, and thus have each test make their own IrcSocketFactory and respective IrcSocket (or even multiple IrcSockets). And since they can do that, there's no reason for them to rely on prior tests, making them a lot less brittle than they currently are.

**Comment by Havvy** [comment]
Err, keeping open for v.2.3.x back-porting as I said....

**Comment by hohl** [comment]
Thank you for the advice. I've already seen your MockSocket, however my work yet have just been some experiments. Testing against a real IRC server is a bad idea anyway.

**Comment by Havvy** [comment]
I never got around to backporting, and I don't plan on doing so now. If somebody wants to backport, they can send a PR to the proper branch, and I'll accept it.
